kenma_app/urls.py
from django.urls import path
from . import views

app_name = 'kenma_app'
urlpatterns = [
   path('', views.IndexViews.as_view(), name='index'),
   path('company', views.CompanyViews.as_view(), name='company'),
   path('service/', views.ServiceViews.as_view(), name='service'),
   path('service/saikenma/', views.SaikenmaViews.as_view(), name='saikenma'),
   path('service/saidanki/', views.SaidankiViews.as_view(), name='saidanki'),
   path('service/sinba/', views.SinbaViews.as_view(), name='sinba'),
   path('service/sizai/', views.SizaiViews.as_view(), name='sizai'),
   path('contact/', views.ContactView.as_view(), name='contact'),
   path('contact/done/', views.DoneViews.as_view(), name='done'),
]

kenma_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kenma_app.urls')),
]

kenma_app/models.py
from django.db import models

# Create your models here.

kenma_app/forms.py
from django import forms

CHOICES = (
    ('タイトルを選択してください','タイトルを選択してください'),
    ('粉砕刃','粉砕刃'),
    ('チッパーナイフ','チッパーナイフ'),
    ('スリッター', 'スリッター'),
    ('裁断刃','裁断刃'),
    ('製袋刃','製袋刃'),
    ('台切り','台切り'),
    ('その他','その他'),
)

class ContactForm(forms.Form):
   name = forms.CharField(label='お名前', max_length=50, required=True,)
   email = forms.EmailField(label='メールアドレス', required=True,)
   select = forms.ChoiceField(widget=forms.Select,choices=CHOICES,label="タイトル")
   message = forms.CharField(label='メッセージ', required=True, widget=forms.Textarea)

kenma_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, EmailMessage
from .forms import ContactForm
import textwrap

class IndexViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/index.html')  

class CompanyViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/company.html')  

class ServiceViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/service.html')  

class SaikenmaViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/saikenma.html')  

class SaidankiViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/saidanki.html')  

class SinbaViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/sinba.html')  

class SizaiViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/sizai.html')  

class ContactView(View):
   def get(self, request, *args, **kwargs):
      form = ContactForm(request.POST or None)
      return render(request, 'kenma_app/contact.html', {'form': form})

   def post(self, request, *args, **kwargs):
      form = ContactForm(request.POST or None)
      if form.is_valid():
          name = form.cleaned_data['name']
          message = form.cleaned_data['message']
          select = form.cleaned_data['select']
          email = form.cleaned_data['email']
          subject = 'お問い合わせありがとうございます。'
          contact = textwrap.dedent('''
             ※このメールはシステムからの自動返信です。

             {name} 様
            
             お問い合わせありがとうございました。
             以下の内容でお問い合わせを受け付けました。
             内容を確認させていただき、ご返信させていただきますので、少々お待ちください。

             ----------------------------------

             ・お名前
             {name}

             ・メールアドレス
             {email}

             ・タイトル
             {select}

             ・メッセージ
             {message}
             -----------------------------------
             株式会社　長町研磨
             〒700-0943
             岡山県岡山市南区新福1-14-4
             TEL 086-26-4-4111
             営業時間 8:15~17:00（月~金）
             WEB: https://www.nagamachi-kenma.com/
          ''').format(
             name=name,
             email=email,
             select=select,
             message=message
          )
          to_list = [email]
          bcc_list = [settings.EMAIL_HOST_USER]

          try:
             message = EmailMessage(subject=subject, body=contact, to=to_list,bcc=bcc_list)
             message.send()
          except BadHeaderError:
             return HttpResponse('無効なヘッダが検出されました。')
          return redirect('kenma_app:done')

      return render(request, 'kenma_app/contact.html',
                   {'form': form})       


class DoneViews(View):
  def get(self, request, *args, **kwargs):   
    return render(request, 'kenma_app/done.html')  

templates/base.html
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <meta name="description" content="新刃(粉砕、スリッター、裁断、その他の刃物)の販売から、再研磨なら岡山に拠点を置く長町研磨にお任せ！高品質、迅速に対応いたします。"/>
   <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
   <title>(株)長町研磨-Official WebSite-</title>
   <link rel="icon" type="image/x-icon" href="img/service/favicon.ico">
   <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="{% static 'css/styles.css' %}">
 </head>
 <body>
 {% include 'header.html'%}
   {% block content %} 
   {% endblock %} 
  {% include 'footer.html'%}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
  <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
 </body>
</html>

templates/footer.html
   <!-- Footer-->
   <footer class="bg-light py-5">
    <div class="container"><div class="text-center">© {{ current_year }} - 株式会社 長町研磨</div></div>
</footer>

templates/ga.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-140383726-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-140383726-3');
</script>

templates/header.html
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'kenma_app:index' %}"><img class="rounded mb-1" src="/static/img/naga_ken_logo.jpeg" alt="長町研磨のロゴ" width="45" height="45"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link js-scroll-trigger text-danger" href="{% url 'kenma_app:service' %}">⚠︎本社移転について⚠︎</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'kenma_app:service' %}">事業内容</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'kenma_app:company' %}">会社概要</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'kenma_app:contact' %}">お問い合わせ</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger insta" href="https://www.instagram.com/nagamachi_kenma/" target="blank"><i class="fab fa-instagram fa-lg"></i> Instagram</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger twitter" href="https://twitter.com/VEijjttgIUUGH6k" target="blank"><i class="pa-2 fab fa-twitter fa-lg"></i> Twitter</a></li>
                
            </ul>
        </div>
    </div>
</nav>

templates/kenma_app/company.html
{% extends 'base.html' %}
{% block content %}   
<header class="company-masthead">
  <div class="container h-50 align-items-center justify-content-center">    
      <h1 class="text-white font-weight-bold text-center">会社概要</h1>
      <hr class="my-4"/>
  </div>
</header>

<table class="table table-hover container my-5 text-center">
  <tbody>
    <tr>
      <th scope="row">会社名</th>
      <td>株式会社 長町研磨</td>
    </tr>
    <tr>
      <th scope="row">本社住所</th>
      <td>岡山県岡山市南区新福1-8-4</td>
    </tr>
    <tr>
      <th scope="row">代表者</th>
      <td>代表取締役社長 　長町 拓哉</td>
    </tr>
    <tr>
      <th scope="row">電話番号 / FAX </th>
      <td><a href="tel:086-264-4111">086-264-4111</a> / 086-264-3909</td>
    </tr>
    <tr>
      <th scope="row">創業</th>
      <td>1960年</td>
    </tr>
    <tr>
      <th scope="row">資本金</th>
      <td>1000万円</td>
    </tr>
    <tr>
      <th scope="row" class="pt-5">事業内容</th>
      <td>裁断刃、工業刃物の再研磨<br>
        新品・中古裁断機の販売及びメンテナンス<br>
      <a href="http://www.katsuda-works.co.jp/" target="_blank">(勝田製作所販売代理店)</a><br>
        印刷関連等の材料販売</td>
    </tr>
    <tr>
      <th scope="row">取引金融機関</th>
      <td>中国銀行 / 三井住友銀行 / 岡山信用金庫</td>
    </tr>
    <tr>
      <th scope="row">営業時間/休日</th>
      <td>8:15〜17:00/土日祝</td>
    </tr>
    {% comment %} <tr>
      <th scope="row">その他/テクノロジー事業</th>
      <td><a href="https://digital-tree.xyz/" target="_blank">©︎ Digital Tree</a></td>
    </tr> {% endcomment %}
  </tbody>
</table>

<div class="related__company">
<h2 class="text-center mb-3">取引先一覧<span style="font-size: 15px;">(敬称略/順不同)</span></h2>

<table class="table table-borderless">
  <tbody>
    <tr>
      <td class="text-center"><a href="https://www.dnp.co.jp/" target="_blank">大日本印刷</a></td>
      <td class="text-center"><a href="http://www.katsuda-works.co.jp/" target="_blank">勝田製作所</a></td>
      <td class="text-center"><a href="http://www.okayamaseishi.co.jp/" target="_blank">岡山製紙</a></td>
    </tr>
    <tr>
      <td class="text-center"><a href="https://www.okr-ind.co.jp/" target="_blank">オークラプロダクツ</a></td>
      <td class="text-center"><a href="http://www.ohinasama.jp/index.html" target="_blank">日本貿易産業</a></td>
      <td class="text-center"><a href="http://www.sid-soken.jp/" target="_blank">SID創研</a></td>
    </tr>
    <tr>
      <td class="text-center"><a href="http://www.toyoknife.co.jp/" target="_blank">東洋刃物</a></td>
      <td class="text-center"><a href="http://okayama-kami.co.jp/" target="_blank">岡山紙商事</a></td>
      <td class="text-center"><a href="https://www.fukuda-web.co.jp/" target="_blank">福田刃物</a></td>
    </tr>
    <tr>
      <td class="text-center"><a href="https://www.kenseido.co.jp/" target="_blank">研精堂印刷</a></td>
      <td class="text-center"><a href="http://www.asahi-housou.jp/" target="_blank">旭包装</a></td>
      <td class="text-center"><a href="https://www.meditec-japan.co.jp/" target="_blank">メディテックジャパン</a></td>
    </tr>
    <tr>
      <td class="text-center"><a href="http://www.shinko-pt.co.jp/" target="_blank">シンコー印刷</a></td>
      <td class="text-center"><a href="https://www.e-books.co.jp/" target="_blank">ブックス</a></td>
      <td class="text-center"><a href="/">西日本果実袋</a></td>
    </tr>
  </tbody>
</table>
<p class="text-center text-secondary">その他多数、、、</p>
      
</div>
     
{% endblock %}   

templates/kenma_app/contact.html
{% extends 'base.html' %}
{% block content %}   

<header class="contact-masthead">
  <div class="container h-50 align-items-center justify-content-center">    
      <h1 class="text-white font-weight-bold text-center">お問い合わせ</h1>
      <hr class="my-4"/>
  </div>
</header>
<div class="line text-center mt-3">
  <h5>Lineからもお問い合わせ受け付けています。<i class="far fa-hand-point-down fa-lg"></i></h5>
  <a href="https://lin.ee/UUFhZgk" target="_blank"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="50" border="0"></a>
</div>
<div class="container my-5">
<form action="{% url 'kenma_app:contact' %}" method="POST">
 {% csrf_token %}
 <label for="id_name" class="sr-only">お名前</label>
 <input class="form-control mb-3" name="name" maxlength="50" required="" id="id_name" type="text" placeholder="お名前">

 <label for="id_email" class="sr-only">メールアドレス</label>
 <input type="email" name="email" required="" id="id_email" placeholder="メールアドレス" class="form-control mb-3">

 <label for="id_select" class="sr-only">タイトル:</label>
 <select name="select" class="custom-select mb-3" id="id_select">
  <option value="タイトルを選択してください">タイトルを選択してください</option>
  <option value="粉砕刃">粉砕刃</option>
  <option value="チッパーナイフ">チッパーナイフ</option>
  <option value="スリッター">スリッター</option>
  <option value="裁断刃">裁断刃</option>
  <option value="製袋刃">製袋刃</option>
  <option value="台切り">台切り</option>
  <option value="その他">その他</option>
</select>

 <label for="id_message" class="sr-only">メッセージ:</label>
 <textarea name="message" style="height: 300px;" cols="40" rows="10" required="" id="id_message" placeholder="メッセージ" class="form-control mb-3"></textarea>

<button type="submit" class="btn btn-block btn-outline-success">送信する</button>
</form>
</div>
{% endblock %}

templates/kenma_app/done.html
{% bootstrap_css %} 
{% bootstrap_javascript jquery='full' %}
<script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
<div class="m-5 text-center">
<div class="card d-inline-block">
 <div class="card-body p-4">
   <h4 class="card-title">お問い合わせありがとうございます。</h4>
  <hr>
   <a href="{% url 'kenma_app:index' %}"><button type="button" class="btn btn-success"><i class="fas fa-home"></i>トップページへ</button></a>
 </div>
</div>
</div>

templates/kenma_app/index.html
{% extends 'base.html' %}
{% block content %}   
      <!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="sns d-lg-none">
                <a class="insta mr-3 p-2 rounded" href="https://www.instagram.com/nagamachi_kenma/" target="blank"><i class="fab fa-instagram fa-lg"></i> Instagram</a>
                <a class="twitter p-2 rounded" href="https://twitter.com/VEijjttgIUUGH6k" target="blank"><i class="pa-2 fab fa-twitter fa-lg"></i> Twitter</a>
            </div>
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">研ぎ澄まされた高品質の刃物</h1>
                <hr class="my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">60年以上の経験と創意工夫で21世紀の刃物業界に穴を開ける！</p>
                <a class="btn-success text-decoration-none btn-xl" href="{% url 'kenma_app:saikenma' %}">再研磨価格表</a>
            </div>
        </div>
    </div>
</header>

{% comment %} 本社移転のお知らせ {% endcomment %}
<section class="page-section border border-danger rounded container mt-3">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0 text-danger">本社移転のお知らせ！</h2>
                        <hr class="my-4"/>
                        <p class="mb-4 text-muted">2021年5月1日より、本社移転のため住所が変更します。<br>新しい住所　<span class="text-danger">岡山市南区新福1-8-4</span><br>尚、電話/FAX番号の変更はございません。<br>詳しくは<a class="text-danger" href="" class="text-decoration-none">⚠︎本社移転について⚠︎</a>をご覧ください。</p>
                    </div>
                </div>
            </div>
        </section>


        <!-- About-->
        <section class="page-section about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">長町研磨について</h2>
                        <hr class="my-4"/>
                        <p class="mb-4 text-muted">1960年に岡山県岡山市に創業しました。<br>以来、印刷関連の裁断刃と工業用刃物（粉砕刃）をメインに成長してきました。<br>その後、裁断機メーカーの<a href="http://www.katsuda-works.co.jp/" target="_blank" class="text-decoration-none">勝田製作所</a>の販売代理店として、主に岡山県内の裁断機の販売〜アフターケアを、お手伝いさせていただいております。<br>現在では、スリッター刃（丸刃）の再研磨も内製化に舵を切り現在に至ります。</p>
                        <!-- <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a> -->
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <section class="page-section bg-light" id="services">
            <div class="container">
                <h2 class="text-center mt-0">事業内容</h2>
                <hr class="my-4">
                <div class="row">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <a class="text-decoration-none" href="{% url 'kenma_app:saikenma' %}">
                            <i class="fas fa-4x fa-gem mb-4"></i>
                            <h3 class="mb-2 text-muted">工業用刃物研磨</h3>
                            <p class="text-muted mb-0">粉砕刃〜スリッターまで、様々な形状、材質、サイズの再研磨を行います。</p>
                        </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <a class="text-decoration-none" href="{% url 'kenma_app:saidanki' %}">
                            <i class="fas fa-4x fa-industry mb-4"></i>
                            <h3 class="mb-2 text-muted">裁断機の販売</h3>
                            <p class="text-muted mb-0">裁断機の新台〜中古、オーバーホール済みなどの販売をメインに、印刷関連の機械も販売しています。</p>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <a class="text-decoration-none" href="{% url 'kenma_app:sizai' %}">
                            <i class="fas fa-4x fa-shopping-bag mb-4"></i>
                            <h3 class="mb-2 text-muted">印刷関連の資材販売</h3>
                            <p class="text-muted mb-0">印刷・製本機関連の、様々な資材の販売を行っています。</p>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <a class="text-decoration-none" href="#">
                            <i class="fas fa-4x fa-question mb-4"></i>
                            <h3 class="mb-2 text-muted">その他</h3>
                            <p class="text-muted mb-0">coming soon...</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Instagram -->
        <h2 class="my-5 text-center insta">Instagram <i class="fab fa-instagram"></i></h2>
        <div class="container text-center" id="insta">
        </div>
        <p class="text-center my-5">
        <button type="button" class="insta btn"><a href="https://www.instagram.com/nagamachi_kenma/" target="blank" class="insta">もっと見る</a></button>
    </p>
        <!-- Call to action-->
        <section class="page-section h-100 bg-dark text-white map">
            <div class="container text-center">
                <h2 class="my-5">アクセス</h2>
                <hr class="text-white my-4">
                <h3>
                    〒700-0943<br>
                岡山県岡山市南区新福1-14-4<br>
                営業時間　8:15〜17:00<br>
                定休日　土日 / 祝</h3>
                <a href="{% url 'kenma_app:company' %}"><p class="btn btn-success btn-lg">詳細</p></a>
            </div>
        </section>
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">お問い合わせ</h2>
                        <hr class="my-4"/>
                        <a href="{% url 'kenma_app:contact' %}"><i class="far fa-envelope fa-4x"></i></a>
                        <p class="text-muted mt-5">新刃の作製から再研磨、裁断機の販売メンテナンスまで何でもお問い合わせください。</p>

                    </div>
                </div>    
                </div>
            </div>
        </section>
{% endblock %}   

templates/kenma_app/iten.html
{% extends 'base.html' %}
{% block content %}  

{% endblock %}   

templates/kenma_app/saidanki.html
{% extends 'base.html' %}
{% block content %}   
<header class="saidanki-masthead">
  <div class="container h-50 align-items-center justify-content-center">    
      <h1 class="text-white font-weight-bold text-center">裁断機</h1>
      <hr class="my-4" />
  </div>
</header>

<div class="container">
  <div class="row my-5">
    <div class="card my-2 col-md-6 col-9 mx-auto px-0">
      <img src="/static/img/service/in-dansai1.jpg" class="card-img-top" alt="裁断機の運搬から設置">
    </div>
    <div class="card my-2 col-md-6 col-9 mx-auto px-0">
      <img src="/static/img/service/in-dansai2.jpg" class="card-img-top" alt="裁断機の修理">
    </div>
    <div class="card my-2 col-md-6 col-9 mx-auto px-0">
      <img src="/static/img/service/in-dansai3.jpg" class="card-img-top" alt="裁断機の運搬から設置">
    </div>
    <div class="card my-2 col-md-6 col-9 mx-auto px-0">
      <img src="/static/img/service/in-dansai4.jpg" class="card-img-top" alt="裁断機の修理">
    </div>
  </div>
</div>
{% endblock %}   

templates/kenma_app/service.html
{% extends 'base.html' %}
{% block content %}   
<header class="service-masthead">
  <div class="container h-50 align-items-center justify-content-center">    
      <h1 class="text-white font-weight-bold text-center">事業内容</h1>
      <hr class="my-4" />
  </div>
</header>
<div class="container-fuid">
<div class="row my-5 mr-0 align-items-center justify-content-center">
<div class="card col-10 col-md-5 m-2" style="width: 18rem;">
  <img src="/static/img/service/chipper.jpg" class="card-img-top" alt="粉砕刃の画像">
  <div class="card-body">
    <h3 class="card-title">刃物の再研磨</h3>
    <p class="card-text">工業刃物（粉砕刃）/ スリッター刃 / 裁断刃 / その他</p>
    <a href="{% url 'kenma_app:saikenma' %}" class="btn btn-success">もっと見る</a>
  </div>
</div>
<div class="card col-10 col-md-5 m-2" style="width: 18rem;">
  <img src="/static/img/service/saidanki.png" class="card-img-top" alt="裁断機の画像">
  <div class="card-body">
    <h3 class="card-title">裁断機の販売</h3>
    <p class="card-text">裁断機（新台、中古）/ 紙揃え / 帯かけ機 </p>
    <a href="{% url 'kenma_app:saidanki' %}" class="btn btn-success">もっと見る</a>
  </div>
</div>
<div class="card col-10 col-md-5 m-2" style="width: 18rem;">
  <img src="/static/img/service/sizai.png" height="340" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-title">印刷資材の販売</h3>
    <p class="card-text">針金 / シリコンスプレー / エアースプレー / ボンド（ホットメルト、トヨメルトなど）/ 定規（裁断機用）/ 各種オイル・グリス
      etc...</p>
    <a href="{% url 'kenma_app:sizai' %}" class="btn btn-success">もっと見る</a>
  </div>
</div>
<div class="card col-10 col-md-5 m-2" style="width: 18rem;">
  <img src="/static/img/naga_ken_logo.jpeg" height="365" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-title">その他</h3>
    <p class="card-text">coming soon...</p>
    <a href="#" class="btn btn-success">もっと見る</a>
  </div>
</div>

</div>
</div>
{% endblock %}   

templates/kenma_app/sizai.html
{% extends 'base.html' %}
{% block content %}   
<header class="sizai-masthead">
  <div class="container h-50 align-items-center justify-content-center">    
      <h1 class="text-white font-weight-bold text-center">資材</h1>
      <hr class="my-4" />
  </div>
</header>

<div class="container">
  <div class="row my-5">
    <div class="card my-2 col-md-4 col-9 mx-auto px-0">
      <img src="/static/img/service/sizai/sizai1.png"  class="card-img-top h-80" alt="製本用針金">
    </div>
    <div class="card my-2 col-md-4 col-9 mx-auto px-0">
      <img src="/static/img/service/sizai/sizai2.png" class="card-img-top" alt="パーツクリーナー">
    </div>
    <div class="card my-2 col-md-4 col-9 mx-auto px-0">
      <img src="/static/img/service/sizai/sizai6.png" class="card-img-top" alt="シリコンエアゾール">
    </div>
    <div class="card my-2 col-md-4 col-9 mx-auto px-0">
      <img src="/static/img/service/sizai/sizai4.png" class="card-img-top" alt="シリコンエアゾール">
    </div>
    <div class="card my-2 col-md-4 col-9 mx-auto px-0">
      <img src="/static/img/service/sizai/sizai5.png" class="card-img-top" alt="ボンド">
    </div>
    <div class="card my-2 col-md-4 col-9 mx-auto px-0">
      <img src="/static/img/service/sizai/sizai3.png" class="card-img-top" alt="ボンド">
    </div>
  </div>
  <p class="text-center my-4 font-weight-bold">印刷、製本関連の資材は、上記以外にも多数取り扱っています。<a href="{% url 'kenma_app:contact' %}">お問い合わせください。</a></p>
</div>   
{% endblock %}   